common/models/News.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $title
 * @property string $ukr_title
 * @property string $content
 * @property string $ukr_content
 * @property string $image
 * @property string $create_date
 * @property integer $status
 * @property integer $priority
 * @property integer $author_id
 */
class News extends \yii\db\ActiveRecord
{
    public $imageUp;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'ukr_content'], 'string'],
            [['create_date', 'image'], 'safe'],
            [['image'], 'file', 'extensions'=>'jpg, gif, png'],
            [['status', 'author_id', 'priority'], 'integer'],
            [['title','content','image'], 'required'],
            [['title', 'ukr_title'], 'string', 'max' => 255],
        ];
    }


    public function beforeSave($insert)
    {
        $this->author_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'ukr_title' => 'Укр.Заголовок',
            'content' => 'Контент',
            'ukr_content' => 'Укр.Контент',
            'image' => 'Обложка',
            'imageUp' => 'Обложка',
            'create_date' => 'Дата создания',
            'status' => 'Статус',
            'author_id' => 'Author ID',
            'priority' => 'Приоритет',
        ];
    }
}

backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\News;
use common\models\NewsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

use yii\web\UploadedFile;
use yii\helpers\Url;
use yii\helpers\FileHelper;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],

            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions'=>['login','error'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions'=>['index','update','create','delete','view'],
                        'roles' => ['admin'],
                    ],
                    [
                        'allow' => true,
                        'actions'=>['index','create','update','view',],
                        'roles' => ['moder'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['user'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new News();
        $model->create_date = date('Y-m-d H:i:s');
        if ($model->load(Yii::$app->request->post())) {
            // get the uploaded file instance. for multiple file uploads
            // the following data will return an array
            $image = UploadedFile::getInstance($model, 'image');
            // store the source file name
            $tmp = explode('.', $image->name);
            $ext = end($tmp);
            // generate a unique file name
            $model->image = Yii::$app->security->generateRandomString().".{$ext}";

            // the path to save file, you can set an uploadPath
            // in Yii::$app->params (as used in example below)
            $path = Url::to(Yii::$app->params['uploadPath']) . $model->image;
            if($model->save()){
                $image->saveAs($path);
                return $this->redirect(['view', 'id'=>$model->id]);
            } else {
                // error in saving model
            }
        }
        return $this->render('create', [
            'model'=>$model,
        ]);


    }

    public function actionCkeUpload()
    {

        $mime_allowed = array(
            'image/jpeg',
            'image/png',
            'image/gif'
        );

        $uploadedFile = UploadedFile::getInstanceByName('upload');
        $mime = FileHelper::getMimeType($uploadedFile->tempName);
        $file = time()."_".$uploadedFile->name;

        $url = Yii::getAlias('@frontendUploads').'/ckeditor/'.$file;
        $uploadPath = Yii::getAlias('@frontend').'/web/uploads/ckeditor/'.$file;
        //extensive suitability check before doing anything with the file…
        if ($uploadedFile==null)
        {
            $message = "Нет загруженного файла.";
        }
        else if ($uploadedFile->size == 0)
        {
            $message = "Не определен размер файл.";
        }
        else if (!in_array ($mime, $mime_allowed))
        {
            $message = "The image must be in either JPG or PNG format. Please upload a JPG or PNG instead.";
        }
        else if ($uploadedFile->tempName==null)
        {
            $message = "You may be attempting to hack our server. We're on to you; expect a knock on the door sometime soon.";
        }
        else {
            $message = "";
            $move = $uploadedFile->saveAs($uploadPath);
            if(!$move)
            {
                $message = "Error moving uploaded file. Check the script is granted Read/Write/Modify permissions.";
            }
        }
        $funcNum = $_GET['CKEditorFuncNum'] ;
        echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url', '$message');</script>";
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            // get the uploaded file instance. for multiple file uploads
            // the following data will return an array
            if(UploadedFile::getInstance($model, 'imageUp')){
                $image = UploadedFile::getInstance($model, 'imageUp');
                // store the source file name
                $tmp = explode('.', $image->name);
                $ext = end($tmp);
                // generate a unique file name
                $model->image = Yii::$app->security->generateRandomString().".{$ext}";

                // the path to save file, you can set an uploadPath
                // in Yii::$app->params (as used in example below)
                $path = Url::to(Yii::$app->params['uploadPath']) . $model->image;
                if($model->save()){
                    $image->saveAs($path);
                    return $this->redirect(['view', 'id'=>$model->id]);
                } else {
                    // error in saving model
                }
            }
                $model->update();
                return $this->redirect(['view', 'id'=>$model->id]);

        }
        return $this->render('update', [
            'model'=>$model,
        ]);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/news/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\Url;
use dosamigos\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model common\models\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin([
        'options'=>['enctype'=>'multipart/form-data'] // important
    ]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ukr_title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->widget(CKEditor::className(), [
        'options' => ['rows' => 6 ],
        'preset' => 'standard',
        'clientOptions' => [
            'language'=>'ru',
            'filebrowserUploadUrl' => Url::to(['news/cke-upload']),
            'inline'=>true,
        ]
    ]) ?>

    <?= $form->field($model, 'ukr_content')->widget(CKEditor::className(), [
        'options' => ['rows' => 6 ],
        'preset' => 'standard',
        'clientOptions' => [
            'language'=>'ru',
            'filebrowserUploadUrl' => Url::to(['news/cke-upload']),
            'inline'=>true,
        ]

    ]) ?>

    <?= $model->isNewRecord ? $form->field($model, 'image')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => false,],
        'pluginOptions'=>[
            'allowedFileExtensions'=>['jpg','gif','png'],
            'showUpload' => false,
            'initialPreview' => [
                $model->image ? Html::img(Yii::getAlias('@frontendUploads').'/'.$model->image, ['class'=>'file-preview-image', 'alt'=>$model->title, 'title'=>$model->title]) : null,
            ],
            'overwriteInitial'=> true,
        ],
    ]) : $form->field($model, 'imageUp')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => false,],
        'pluginOptions'=>[
            'allowedFileExtensions'=>['jpg','gif','png'],
            'showUpload' => false,
            'initialPreview' => [
                $model->image ? Html::img(Yii::getAlias('@frontendUploads').'/'.$model->image, ['class'=>'file-preview-image', 'alt'=>$model->title, 'title'=>$model->title]) : null,
            ],
            'overwriteInitial'=> true,
        ],
    ]) ?>


    <?= $form->field($model, 'status')->dropDownList([
        '0' => 'Не опубликованная',
        '1' => 'Опубликованная'
    ]) ?>
    <?= $form->field($model, 'priority')->dropDownList([
        '0' => 'Не задано',
        '1' => 'Топ'
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/news/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\SearchNews */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'ukr_title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'ukr_content') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/news/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\News */

$this->title = 'Создать новость';
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/news/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\StringHelper;
/* @var $this yii\web\View */
/* @var $searchModel common\models\SearchNews */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Новости';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать новость', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'title',
            [
                'attribute' => 'image',
                'format' => 'html',
                'value' => function ($data) {
                    return Html::img(Yii::$app->urlManagerFrontEnd->baseUrl.'/uploads/'. $data['image'],
                        ['width' => '100px']);
                },
            ],
             'create_date',
            [
                'attribute'=>'status',
                'value'=>function($data){
                    return ($data->status==1 ? "Опубликованная" : "Не опубликованная");
                }
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\News */

$this->title = 'Обновить новость: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="news-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\StringHelper;
/* @var $this yii\web\View */
/* @var $model common\models\News */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Действительно хотите удалить?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'title',
            'ukr_title',
            [
                'attribute' => 'content',
                'format' => 'text',
                'value' => call_user_func( function ($model) {
                    return StringHelper::truncate($model->content, 200);
                }, $model),
            ],
            [
                'attribute' => 'image',
                'format' => 'html',
                'value' => call_user_func( function ($data) {
                    return Html::img(Yii::getAlias('@frontendUploads').'/'. $data['image'],
                        ['width' => '100px']);
                }, $model),
            ],
            'create_date',
            [
                'attribute'=>'status',
                'value'=>call_user_func(function($data){
                    return ($data->status==1 ? "Опубликованная" : "Не опубликованная");
                },$model),
            ],
        ],
    ]) ?>

</div>